"""category_fields_length

Revision ID: 5d2964f3a837
Revises: 98ca051df4f0
Create Date: 2024-08-25 05:37:10.527799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d2964f3a837"
down_revision: Union[str, None] = "98ca051df4f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category",
        "slug",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.String(length=140),
        existing_nullable=False,
    )

    op.alter_column(
        "category",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category",
        "slug",
        existing_type=sa.String(length=140),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )

    op.alter_column(
        "category",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
