"""category_table_uqn

Revision ID: 7b3b17cf61bb
Revises: 5d2964f3a837
Create Date: 2024-08-26 12:36:34.622319

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b3b17cf61bb"
down_revision: Union[str, None] = "5d2964f3a837"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unq_category_name_level_constraint", "category", ["name", "level"]
    )
    op.create_unique_constraint("unq_category_slug_constraint", "category", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unq_category_name_level_constraint", "category", type_="unique")
    op.drop_constraint("unq_category_slug_constraint", "category", type_="unique")
    # ### end Alembic commands ###
