"""seasonal_event_product_link22

Revision ID: 8a99cff8785b
Revises: 15a1bb05deed
Create Date: 2024-08-31 19:40:21.108695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a99cff8785b"
down_revision: Union[str, None] = "15a1bb05deed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product", "seasonal_event", existing_type=sa.INTEGER(), nullable=True
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product", "seasonal_event", existing_type=sa.INTEGER(), nullable=False
    )

    # ### end Alembic commands ###
