"""product_line_table

Revision ID: a6c7e7645754
Revises: 4077b4589568
Create Date: 2024-08-31 13:23:15.273532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6c7e7645754"
down_revision: Union[str, None] = "4077b4589568"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_line",
        "price",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unq_product_line_sku_constraint", "product_line", ["sku"]
    )
    op.create_unique_constraint(
        "unq_product_line_order_product_id_constraint",
        "product_line",
        ["order", "product_id"],
    )
    op.alter_column(
        "product_line",
        "price",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
    )
    op.create_unique_constraint("unq_product_slug_constraint", "product", ["slug"])
    op.create_unique_constraint("unq_product_name_constraint", "product", ["name"])
    op.create_unique_constraint("unq_category_slug_constraint", "category", ["slug"])
    op.create_unique_constraint(
        "unq_category_name_level_constraint", "category", ["name", "level"]
    )
    # ### end Alembic commands ###
