"""product_table

Revision ID: af323ca2bca2
Revises: 7b3b17cf61bb
Create Date: 2024-08-30 15:18:19.669908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af323ca2bca2"
down_revision: Union[str, None] = "7b3b17cf61bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "pid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_digital", sa.Boolean(), server_default="False", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.Column(
            "stock_status",
            sa.Enum("outofstock", "available", "ordered", name="status_enum"),
            server_default="outofstock",
            nullable=False,
        ),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pid"),
    )
    op.create_foreign_key(None, "category", "category", ["parent_id"], ["id"])
    op.create_unique_constraint("unq_product_name_constraint", "product", ["name"])
    op.create_unique_constraint("unq_product_slug_constraint", "product", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "category", type_="foreignkey")
    op.drop_constraint("unq_category_name_level_constraint", "category", type_="unique")
    op.drop_constraint("unq_category_slug_constraint", "category", type_="unique")
    op.drop_constraint("product_pid_key", "product", type_="unique")
    op.drop_constraint("unq_product_name_constraint", "product", type_="unique")
    op.drop_constraint("unq_product_slug_constraint", "product", type_="unique")
    op.drop_table("product")
    # ### end Alembic commands ###
