"""seasonal_event_tbl

Revision ID: b3775498c1c0
Revises: faa55e3fff02
Create Date: 2024-08-31 19:28:54.195206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3775498c1c0"
down_revision: Union[str, None] = "faa55e3fff02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seasonal_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_unique_constraint(
        "unq_seasonal_event_name_constraint", "seasonal_event", ["name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("seasonal_event")
    # ### end Alembic commands ###
