"""attribute_tbl

Revision ID: f743fd1c884b
Revises: 8a99cff8785b
Create Date: 2024-08-31 19:52:35.244965

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f743fd1c884b"
down_revision: Union[str, None] = "8a99cff8785b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.CheckConstraint("LENGTH(name) > 0", name="attribute_name_length_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_attribute_name"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unq_seasonal_event_name_constraint", "seasonal_event", ["name"]
    )
    op.create_unique_constraint(
        "unq_product_line_sku_constraint", "product_line", ["sku"]
    )
    op.create_unique_constraint(
        "unq_product_line_order_product_id_constraint",
        "product_line",
        ["order", "product_id"],
    )
    op.create_unique_constraint(
        "unq_product_image_order_product_line_id_constraint",
        "product_image",
        ["order", "product_line_id"],
    )
    op.create_unique_constraint("unq_product_slug_constraint", "product", ["slug"])
    op.create_unique_constraint("unq_product_name_constraint", "product", ["name"])
    op.create_unique_constraint("unq_category_slug_constraint", "category", ["slug"])
    op.create_unique_constraint(
        "unq_category_name_level_constraint", "category", ["name", "level"]
    )
    op.drop_table("attribute")
    # ### end Alembic commands ###
